apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ns9adwldd-nodejs 
  janus-idp.io/tekton: ns9adwldd-nodejs
  backstage.io/kubernetes-id: ns9adwldd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ns9adwldd-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  